### PR TITLE
Adds .NET 6 support

### LINKED ISSUE #19: .NET 6 support
The dotnet-affected tool cannot run on .NET 6.

```
You can invoke the tool using the following command: dotnet-affected
Tool 'dotnet-affected' (version '2.0.0-preview-1') was successfully installed.
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.20.04-x64
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

### PR DESCRIPTION
**Pull request by wterpstra**
Fixes #19

### CODE REVIEW

**Comment by leonardochaia** [comment]
Thanks @wterpstra ! I'll take a look today and see if I can push a new version supporting .NET 6.

**Comment by leonardochaia** [comment]
Ok, so managed to fix CI but there's an issue with the `TraversalProjectOutputFormatter` apparently while building the traversal proj file.

Not sure yet, but I think `Microsoft.Build.Traversal` needs to support net 6

image

I've [created an issue](https://github.com/microsoft/MSBuildSdks/issues/309) to see if we can get some help. I'm unsure what the fix is right now.

In the meantime, perhaps in CI you can use dotnet-affected in a [docker image](https://hub.docker.com/r/lchaia/dotnet-affected) so its not dependent of the SDK version on the host.

Example usage:


```
docker run --rm -v $(System.DefaultWorkingDirectory):/workspace \
        lchaia/dotnet-affected:2.0.0-preview-1 \
        --verbose \
        --output-dir /workspace/dotnet \
        --from $(SourceCommit) \
        --to $(TargetCommit) \
        --format text
```

**Comment by wterpstra** [comment]
Hey Leo, thanks for fixing the CI, it's pity the Microsoft.Build.Traversal stuff is still behind. I did manage to get it working, you can just have the .NET 5 SDK installed side by side and it works like a charm!

**Comment by leonardochaia** [comment]
To give an update on .NET 6 support, we are waiting for .NET 6.0.200 to be released, [which contains the fix](https://github.com/microsoft/MSBuildSdks/issues/309#issuecomment-1009167523) that we need to support .NET 6

I've managed to build and run tests against net6, net5, and net3.1 using this branch and dotnet 6.0.200 daily builds, which i've installed using `"$install_script" --install-dir "$dotnet_install_dir" --channel 6.0.2xx --quality preview` in `eng/install-sdk.sh`, so once 6.0.200 is released we should be good to merge and release new packages targeting net6, net5, and net3.1.

**Pull request merged**
