### PR TITLE
Adds support for detecting affected projects for version changes in centrally managed NuGet packages

### PR DESCRIPTION
**Pull request by wterpstra**
Hey Leo,

Figured I'd try my hand at detecting version changes for centrally managed NuGet packages (#22) and resolving it's affected projects. 

It should work as follows:
1. When detecting changes try and resolve a Directory.Packages.props file, this is either a single file somewhere in the repository or in the same directory as the solution file as stated in the [proposal](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions)
2. Diff the Directory.Packages.props file using Git, and resolve a unique list of changed package references using a regular expression from the added or deleted lines
3. Use the `ProjectGraph` to find any projects that reference these packages and add them to the changed projects
4. Existing logic will resolve the affected projects

It's late now, so I'll fix/add unit tests and do some more testing later. For now I'm wondering if you have any feedback or remarks at my first stab at implementing this.

Let me know!

Cheers, 
Wessel

### CODE REVIEW

**Comment by leonardochaia** [comment]
Hey @wterpstra this is great!!

The steps you mention in the PR Description sounds good. I'll try to take a look at the code during the weekend.

Thank you!

**Comment by wterpstra** [comment]
Hey @leonardochaia, I added some unit tests and took the liberty to fix some unit tests that were failing when running on Windows. I opened a new issue for adding unit tests to the GitChangesProvider. I'll change the status to ready for review now. Have a look if you can find the time, no rush.

**Comment by leonardochaia** [comment]
Hey @wterpstra, this is looking good. I like the new tests.

I was thinking that, since we are parsing the Directory.Package.props using a regex, we wouldn't be actually interpreting the file. Stuff like conditions would be ignored, unless I'm missing something.

Perhaps there's a way to do this using MSBuild but I'm not sure how..

**Comment by wterpstra** [comment]
Yes you are right. This will just get a changed line from git and try to parse out the package name so it can be marked as changed. If some itemgroup gets it's condition changes or somone (for whatever reason) decides to have multiple packages referenced on a single line this will break.

I guess we can just pull the source and target versions of the Directory.Packages.props files from git. Maybe we can use the `Microsoft.Build.Evaluation` class to read through the files. 

We can detect changes in the properties of the ItemGroups (by hashing them?). If an ItemGroup changed between the two commits then all NuGets inside them can be considered changed. Same thing goes for the NuGets, we can detect changes in the properties (by hashing?) and if they got changed between the two commits we consider them changed.

**Comment by leonardochaia** [comment]
Hi @wterpstra, I'm out of ideas TBH. I think hashing the ItemGroups would work. Not sure about the performance but I guess eventually we'll have to work on performance overall.

Considering this PR is getting big, perhaps we can merge this PR as an initial implementation with the known caveats, and work on the evaluation of the file in a subsequent PR?
We would publish a new release when the feature is complete. We can publish a pre-release in the meantime if needed.

**Comment by wterpstra** [comment]
Yes sounds good to me, I guess anything is better than nothing for now!

**Comment by leonardochaia** [comment]
Got it. I'll take another look, solve comments and merge it. Hopefully I'll find some time this week.

**Comment by leonardochaia** [comment]
Hi @wterpstra a friend brought [dotnet-outdated](https://github.com/dotnet-outdated/dotnet-outdated) to my attention.

Looks like they do something very similar to what we wanna achieve here. I haven't dig deep into the code but a quick look shows they are using [MSBuild CLI to generate the dependency graph](https://github.com/dotnet-outdated/dotnet-outdated/blob/master/src/DotNetOutdated.Core/Services/DependencyGraphService.cs#L28), which sounds interesting. I'm curious what is faster.

I haven't seen where they do the diff thing yet but wanted to share in case you wanna check it out.

**Comment by leonardochaia** [comment]
Been taking a look at this but I wanna improve the testing situation before merging so that refactors can be applied with ease over these changes.

**Comment by leonardochaia** [comment]
We will merge this PR as is and improve the detection algorithm in the future to support evaluating the Directory.Packages.props file

fixes #22

**Pull request merged**
