### PR TITLE
Update Microsoft.Build.Traversal sdk version to 4.1.0

### PR DESCRIPTION
**Pull request by batkaevruslan**
[Microsoft.Build.Traversal.4.0.0](https://github.com/microsoft/MSBuildSdks/releases/tag/Microsoft.Build.Traversal.4.0.0) added an ability to "to skip projects dynamically in Traversal projects and Visual Studio solution files" that is required for us.

Let's update sdk version to the latest

### CODE REVIEW

**Comment by batkaevruslan** [comment]
@leonardochaia ?

**Comment by leonardochaia** [comment]
Hi @batkaevruslan, sorry for the delay. I'm struggling to find time.

I have one main question: Given dotnet-affected supports netcoreapp3, net6 and net7, do we need to change the traversal SDK version depending on the dotnet version?

**Comment by batkaevruslan** [comment]
@leonardochaia , I think we don't: 
* I've found no information on any net-version requirements https://github.com/microsoft/MSBuildSdks/tree/main/src/Traversal
* I've succesfully built netcoreapp3  with Traversal sdk

image

**Review by leonardochaia — APPROVED** [review]

**Comment by leonardochaia** [comment]
I am good to merge but I am trying to figure out why the github actions aren't running for this PR

**Pull request merged**
