### PR TITLE
Add cache to store repeated dependency tree calcs

### PR DESCRIPTION
**Pull request by megakid**
When running this against a large solution, it was found to be very inefficient - recalculating the same dependency paths again and again.  Added this simple cache to resolve this.  I left this executing for 15mins+ before cancelling.  After this fix, the same command returned in < 5 seconds.

### CODE REVIEW

**Comment by leonardochaia** [comment]
Hi @megakid ! thank you :)

I haven't focused on performance at all. Hopefully all tests pass.
I'll take a look at the code.

**Comment by megakid** [comment]
Thanks. Let me know if I can do anything

**Comment by leonardochaia** [comment]
Hi @megakid, do you wanna take a look at why the tests are failing in unix/windows?

I may find some time to do so during the weekend.

**Comment by megakid** [comment]
Havent had a lot of time to look at this but the test failures look unrelated to my changes - 
The windows OS failed due to a missing file and I cant explain why macos passes and ubuntu fails on a null ref inside the dictionary key.  I am running Mac M1 so I can't check other operating systems easily.

**Pull request merged**
